metadata:
  name: czech-republic-eu-gb
  annotations:
    argocd.argoproj.io/sync-wave: "1699"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    nethopper.io/objectID: 662bb0f7074d9004277c745c
    nethopper.io/cloudID: 65fb2f5e4f7eb03ea16cd4cc
spec:
  source:
    path: guestbook
    repoURL: https://github.com/nethopper2/argocd-example-apps.git
    targetRevision: main
    chart: ""
  destination:
    namespace: default
    name: ""
    server: https://nh-kapi-czech-republic:8080
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
apiVersion: argoproj.io/v1alpha1
kind: Application
